name:                wLPAs
version:             0.1.0.0
github:              "githubuser/wLPAs"
license:             BSD3
author:              "Ruben Zilibowitz"
maintainer:          "ruben@rubenz.net"
copyright:           "2019 Ruben Zilibowitz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Code relating to my mathematics honours thesis on Leavitt path algebras
# category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/wLPAs#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6
- matrix >= 0.2.2
- process >= 1.6
- random >= 1.1

library:
  source-dirs: src

executables:
  wLPAs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wLPAs

tests:
  wLPAs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wLPAs
